/* eslint-disable react/prop-types */
import React from "react";
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (<>
  <Head>
        <title>User profiles web app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      </Head>
  <Component {...pageProps} />
  </>);
}

export default MyApp
